#! /usr/bin/env python

import sys
from darkflow.cli2 import createInstance, detectNumPpl
from darkflow.detectionArgs import theArgs
import cv2
tfnet = createInstance(theArgs)





# Hey David or Cay, 
#   I'm not sure what form you will have the image in so let me know if not supported
#   If you have the path, use "detectNumPpl" with the path paramater
#   Otherwise you'll need the image as opened by opencv -> "cv2.imread" is shown here in example 2
#   The function will return the number of people!

#e.g 1
#using path directly
path = r"C:\Users\Benjamin_de_worsop\Desktop\yolo-object-detection\darkflow\test\yeet\erc_undergnd.jpg"
print(detectNumPpl(tfnet, path=path))

#e.g 2
#using an image 
path2 = r"C:\Users\Benjamin_de_worsop\Desktop\yolo-object-detection\yolo-object-detection\image.jpg"
image = cv2.imread(path2, 1)
print(detectNumPpl(tfnet, image=image))


